apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: ap-northeast-1
  version: "1.30"

availabilityZones: [ap-northeast-1a, ap-northeast-1c, ap-northeast-1d]

vpc:
  # Set to true if you want a private cluster; for test we use public+private subnets managed by eksctl
  nat:
    gateway: HighlyAvailable

managedNodeGroups:
  - name: ng-app
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    volumeSize: 20
    labels: { role: app }
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true

iam:
  withOIDC: true
